# Generated by Django 3.2 on 2021-04-13 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productinventory', '0003_auto_20210413_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('amount_paid', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('order_date', models.DateField(auto_now=True)),
                ('brand_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productinventory.brand')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productinventory.product')),
            ],
        ),
    ]
