# Generated by Django 3.2 on 2021-04-17 19:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email_by',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='pin_code',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
