# Generated by Django 3.2 on 2021-04-13 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productinventory', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='brand_status',
            new_name='available',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='status',
            new_name='available',
        ),
    ]
